schema-version: v2
kind: plugin
metadata:
  name: popcorn-springboot-base-plugin
  display-name: popcorn-springboot-base-plugin
  description: Plugin base para construção de APIs REST com Spring Boot
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
    - Java
    - Spring Boot
  inputs:
    - label: Nome da aplicação
      name: project_name
      type: text
      required: true
    - label: Group_Id do Maven
      name: project_group_id
      type: text
      required: true
      default: "br.com.zup.popcornstudio"
    - label: Artifact_Id do Maven
      name: project_artifact_id
      type: text
      required: true
    - label: Versão do Spring Boot
      name: project_springboot_version
      type: text
      default: 3.1.4
      required: true
    - label: Versão do Java
      name: project_java_version
      type: text
      items:
        - "17"
        - "21"
      default: 17
      required: true
