schema-version: v2
kind: plugin
metadata:
  name: popcorn-springboot-actuator-plugin
  display-name: Spring Boot Actuator plugin
  description: Habilita microsserviço a expor endpoints de Health Checking e Metrics via Spring Boot Actuator
  version: 0.0.2
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  repository: git@github.com:rafaelpontezup/popcorn-studio.git
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
    - Java
    - Spring Boot
  stk-projects-only: false
  inputs:
    - label: Quais endpoints a aplicação deve expor?
      name: actuator_endpoints
      type: multiselect
      required: true
      items:
        - health
        - metrics
        - env
      default: health
      help: Selecione quais endpoints de monitoramento serão expostos pelo Spring Boot Actuator
  computed-inputs:
    actuator_endpoints_joined: "{{actuator_endpoints | join(',')}}"

  hooks:
    ##
    # Edit pom.xml
    # (Using hook type=edit)
    ##
    # - type: edit
    #   path: pom.xml
    #   trigger: after-render    
    #   changes:
    #     - search:
    #         string: "</dependencies>"
    #         insert-before:
    #           snippet: snippets/snippet-pom.xml.jinja
    #         when:
    #           not-exists-snippet: snippets/snippet-pom.xml.jinja
    
    ##
    # Edit pom.xml
    # (Using hook type=edit-xml)
    ##
    - type: edit-xml
      trigger: after-render 
      path: pom.xml
      encoding: UTF-8
      changes:
        - xpath: .//dependencies
          append:
            snippet: snippets/snippet-pom.xml.jinja
          when:
            not-exists: "./dependencies/dependency/artifactId[.='spring-boot-starter-actuator']/.."

    ##
    # Edit application.yaml
    # (Using hook type=edit)
    ##
    # - type: edit
    #   path: src/main/resources/application.yaml
    #   trigger: after-render    
    #   changes:
    #     - insert:
    #         line: -1
    #         snippet: snippets/snippet-application.yaml.jinja
    #         when:
    #           not-exists: "management:"
    
    ##
    # Edit application.yaml
    # (Using hook type=edit-yaml)
    ##
    - type: edit-yaml
      path: src/main/resources/application.yaml
      trigger: after-render
      indent: 4
      encoding: UTF-8
      changes:
        - yamlpath: "$"
          update:
            snippet: snippets/snippet-application.yaml.jinja
          when:
            not-exists: "$.management.endpoints"
