schema-version: v2
kind: plugin
metadata:
  name: popcorn-springboot-data-jpa-plugin
  display-name: Spring Boot Data JPA plugin
  description: Habilta microsserviço com persistência em bancos de dados relacionais com Spring Data JPA e Hibernate
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  repository: git@github.com:rafaelpontezup/popcorn-studio.git
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
    - Java
    - Spring Boot
  stk-projects-only: false
  inputs:
    - label: Escolha um banco de dados relacional (RDBMS)
      name: database_name
      type: text
      items:
        - H2
        - PostgreSQL
      default: H2
      help: Se você não possui infraestrutura pronta, você pode escolher o H2 como banco em memória
    - label: Informe o pacote base do seu projeto
      name: base_package
      type: text
      default: br.com.zup.popcornstudio
      help: Pacote base raiz (group_id + artifact_id)
